### ISSUE TITLE
Mazizone 1.5

### ISSUE THREAD

**Issue by deckspace** [mazi-project/portal#1]
We are commenting on a version of the Mazi toolkit not yet available here!

normal access of the portal seems to respond fine. we can see the Aplications (typo) and Statistics in the menu.. and link to the applications just fine. 

anyway have installed 1.5 to raspberry pi 3 and and connecting via ethernet on port 4567/admin and am logged in (i think) but the login page stays on screen after username and password are entered, preventing view of the various pages from the menu. We can see the many menu items on the left column. Even opening the pages in a new tab still returns the login page. 

reset the default password and rebooted. Same story as above.. will now try clearing browser cache 
...still the same result. will try on another pc via wireless - also note that the applications are not available via ethernet, perhaps this is also controlled via admin panel. ?

**note: The date/time must be set correctly before the admin login is functional.**

 running current Firefox 15.01 64bit on linux Mint.

**Comment by haniavis** [comment]
This one was related to the wrong date of the raspberry, as you correctly mention.

It was an issue only in Firefox, due to the way it handles sessions.

It is now fixed in v1.5.2
