### ISSUE TITLE
permanent footer is distracting 

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#10]
I find the "fixed" footer with the acknowledgement to the project distracting and unnecessary. As is standard practice, the footer could be placed at the end of the page and appear only when someone scrolls down.

**Comment by deckspace** [comment]
I think the fixed header is also distracting.. and doesn't have a purpose other than to carry the title and the alert tab.. (what is that for?) the hamburger could reveal context menus leaving the whole screen clear for use.

**Comment by panosnethood** [comment]
Personally I like the header and I actually think it should stay there permanently to signal that the fact that this is an "offline" space, a MAZI Zone. 

But I would get read of the left sidebar, and instead add links to the most popular applications on the header, together with additional information requested by the administrator (e.g., the location where this MAZI Zone is running).

We could even choose an appropriate colour for the header and "brand" it as the MAZI Zone symbol ...

**Comment by panosnethood** [comment]
And in case an administrator does not like the idea of the header it could be a very simple configuration option to just hide it (in the "introductory" page and/or the running application pages)

**Comment by panosnethood** [comment]
I guess the original issue is resolved (regarding the footer). For the rest, I created a more detailed one: #21
