### ISSUE TITLE
activating monitoring data gets me to an empty page 

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#100]
After I activated the "system activity" data monitoring I went to an empty page with "{"status":"OK"}" written on it. It would be better to stay on the same page (automatically redirected perhaps from the "status" page)

**Comment by haniavis** [comment]
Can you reproduce this issue and send here a screenshot?

If not, and since there is a more stable version now (v2.4.6) we can consider this closed.

**Comment by panosnethood** [comment]
Yes, it happened also yesterday when I activated monitoring data for a 2nd mazi zone. Now I don't remember if I had rebooted after the update. I will check again later today, but let's leave it open for now :-)

**Comment by panosnethood** [comment]
This is still happening. Here is how it looks after I enable the monitoring data (and I have to press "back" to go to the admin panel.

![mazi-bug-status](https://user-images.githubusercontent.com/17811877/41547933-d25bcc86-7321-11e8-86b4-c08020d65438.png)

**Comment by haniavis** [comment]
This is a bug in Firefox. We are working on fixing it in the next release
