### ISSUE TITLE
admin initial set-up (small) inconveniences

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#104]
In my opinion there are two small inconveniences in the initial admin set-up:

1) For many people it is not obvious the "hint" in the first page and they get stuck. I propose to check if the current password is "1234" and if it is not to ask for it. Or even better check if it is the first time that this screen is displayed.

2) I think the location info (and especially the coordinates) should not be obligatory and in the worst case it should be made clear that they are. The first time I arrived on this screen, not being online and not being able to check on google maps (I would give guidelines for openstreet map btw :-)), I decided to skip this step and was redirected back to the first page having to fill all information from scratch. The 2nd time I thought I could just put 0,0 and got redirected again. I spend 10min to get through this screen :-)

**Comment by deckspace** [comment]
Thanks for raising this point Panos, as it gets asked every time we start anyone from scratch with a fresh mazi. Perhaps It's a page to return to once a mazi is up and running, where you could reset the password-essid-date configuration but this would still require the current password be entered. But as these option now exists elsewhere in the dashboard it longer serves a purpose. 

Instead let's just set a password, name the mazi (something.mazi) , offer this as the essid and automatically set the date/time from the logged in PC, all with an option to adjust. Some just won't want to set a location at all. If a location is required then offer some well known gathering points, Bondi beach or Deptford market, somewhere people get together!

**Comment by mgaved** [comment]
I've found the initial login process difficult. 

(1) I got an error message when I added the Lat/Long, it said Please try again by using this format 'latitude, longitude'. But the information under the Location box asks for "Then use the coordinates from the box that appears at the bottom of the screen (eg 39.379012, 22.902813)". 

I was confused from these conflicting instructions as to whether I should be adding single quotes ' ' or brackets ( ) . Small but important action for the dev team will be to make this advice consistent,

(2) My location (52.0250853,-0.7119377) didn;t seem to work, so I used the suggestion from the interface: 39.379012, 22.902813. Does anybody know what the issue might have been? was it too many decimal places? 

(3) I agree there should be a minimum number of fields compulsory, we need to keep the bar to entry as low as possible. I like deckspace's suggestion that an essid is autogenerated from the naming of the mazi, and the user is offered the option to use this or change. 

Keep up the good work, development team, thanks for all your help!

**Comment by ardadouk** [comment]
Hi Mark,

thanks for reporting this. See my answers inline.

> (1) I got an error message when I added the Lat/Long, it said Please try
> again by using this format 'latitude, longitude'. But the information under
> the Location box asks for "Then use the coordinates from the box that
> appears at the bottom of the screen (eg 39.379012, 22.902813)".
>
> I was confused from these conflicting instructions as to whether I should
> be adding single quotes ' ' or brackets ( ) . Small but important action
> for the dev team will be to make this advice consistent,
>
You are supposed to give the location with neither quotes nor brackets for
example 39.379012, 22.902813. It would be helpful if you could suggest a
phrasing that shows this.

(2) My location (52.0250853,-0.7119377) didn;t seem to work, so I used the
> suggestion from the interface: 39.379012, 22.902813. Does anybody know what
> the issue might have been? was it too many decimal places?


It didn't work because you missed the space after the comma. If you used
google maps or openstreetmaps and copy pasted the coordinates it wouldn't
be a problem.

(3) I agree there should be a minimum number of fields compulsory, we need
> to keep the bar to entry as low as possible. I like deckspace's suggestion
> that an essid is autogenerated from the naming of the mazi, and the user is
> offered the option to use this or change.
>

In version 2.5.0 those fields are not mandatory.

Thanks a lot for your input.

Best regards,
Aris

**Comment by mgaved** [comment]
Hi Aris - thanks for quick reply!

(1) I'll think of some text and post it here or to the MAZI tech list, thanks

(2)
> It didn't work because you missed the space after the comma
Can we extend the script behind the form to be able to extract the numbers either side of a comma and throw away all the other characters, so users don't get an error if they add zero spaces, or two spaces, or any other characters?

(3) It's great you've minimised the number of compulsory fields, thanks!

Many thanks to you and the team for all the development work!
Mark
