### ISSUE TITLE
admin settings - SQL password? + default max upload size

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#105]
Hi again, and sorry for spamming :-)

In the admin "settings" it is not obvious what is the current SQL password and I think that it would be better to set as default max upload file 20MB instead of 2MB.

As far as the passwords are concerned, perhaps we need also the possibility for the admin to set a "master" password for all applications and services because otherwise it is very probably that most of them will stay with the "default" password.

**Comment by haniavis** [comment]
default max upload size is now 20MB in v2.5.2
