### ISSUE TITLE
Updating issue: MAZIv2_4_6 claims not connected to the internet (but it is)

### ISSUE THREAD

**Issue by mgaved** [mazi-project/portal#109]
I have a MAZI v2.4.6. I want to update to v2.5. I go to Admin>Check for Updates
The MAZIzone says it is not connected to the internet. However I am connected to the internet in Dual Mode (I am writing this post, for example) . I have tried rebooting the MAZIzone and I still get the same message. I have made sure I have the correct date and time.

As you can see I am connected to the MAZI (ou.mazi) and I have also carried out a ping test to prove I can access the BBC website which is on the internet. 

Can you recommend how I can update to v2.5?

Thanks! (and apologies if I've missed something obvious!)

![no-connection-v2-4-6](https://user-images.githubusercontent.com/18211485/41169814-09d846c2-6b42-11e8-9dbb-155b9c82ec6a.png)

**Comment by mgaved** [comment]
oh, here is the log file if it is useful

D, [2018-06-08 17:21:11 #623] DEBUG -- : request: get/admin_network from ip: 127.0.0.1 params: {"splat"=>[], "captures"=>["admin_network"], "index"=>"admin_network"}
D, [2018-06-08 17:21:11 #623] DEBUG -- : $ sh /root/back-end/current.sh -s -p -c -m
D, [2018-06-08 17:21:11 #623] DEBUG -- : > channel 1
D, [2018-06-08 17:21:11 #623] DEBUG -- : > ssid http://ou.mazi
D, [2018-06-08 17:21:11 #623] DEBUG -- : > password -
D, [2018-06-08 17:21:11 #623] DEBUG -- : > mode "offline"
D, [2018-06-08 17:21:11 #623] DEBUG -- : $ sh /root/back-end/antenna.sh -a
D, [2018-06-08 17:21:11 #623] DEBUG -- : > inactive
D, [2018-06-08 17:21:11 #623] DEBUG -- : $ sh /root/back-end/mazi-router.sh -s
D, [2018-06-08 17:21:14 #623] DEBUG -- : > router unavailable
D, [2018-06-08 17:21:14 #623] DEBUG -- : $ sh /root/back-end/current.sh -w
D, [2018-06-08 17:21:14 #623] DEBUG -- : > device Raspberry pi
D, [2018-06-08 17:21:14 #623] DEBUG -- : $ sh /root/back-end/current.sh -d
D, [2018-06-08 17:21:14 #623] DEBUG -- : > domain portal.mazizone.eu
D, [2018-06-08 17:21:18 #623] DEBUG -- : request: post/exec from ip: 127.0.0.1 params: {"env"=>"sh", "cmd"=>"internet.sh", "mode"=>"dual"}
D, [2018-06-08 17:21:18 #623] DEBUG -- : $ sh /root/back-end/internet.sh -m dual
D, [2018-06-08 17:21:18 #623] DEBUG -- : > # Generated by iptables-save v1.4.21 on Fri Jun  8 17:21:18 2018
D, [2018-06-08 17:21:18 #623] DEBUG -- : > *filter
D, [2018-06-08 17:21:18 #623] DEBUG -- : > :INPUT ACCEPT [1:76]
D, [2018-06-08 17:21:18 #623] DEBUG -- : > :FORWARD ACCEPT [0:0]
D, [2018-06-08 17:21:18 #623] DEBUG -- : > :OUTPUT ACCEPT [1:76]
D, [2018-06-08 17:21:18 #623] DEBUG -- : > COMMIT
D, [2018-06-08 17:21:18 #623] DEBUG -- : > # Completed on Fri Jun  8 17:21:18 2018
D, [2018-06-08 17:21:18 #623] DEBUG -- : > # Generated by iptables-save v1.4.21 on Fri Jun  8 17:21:18 2018
D, [2018-06-08 17:21:18 #623] DEBUG -- : > *nat
D, [2018-06-08 17:21:18 #623] DEBUG -- : > :PREROUTING ACCEPT [0:0]
D, [2018-06-08 17:21:18 #623] DEBUG -- : > :INPUT ACCEPT [0:0]
D, [2018-06-08 17:21:18 #623] DEBUG -- : > :OUTPUT ACCEPT [0:0]
D, [2018-06-08 17:21:18 #623] DEBUG -- : > :POSTROUTING ACCEPT [0:0]
D, [2018-06-08 17:21:18 #623] DEBUG -- : > -A POSTROUTING -o eth0 -j MASQUERADE
D, [2018-06-08 17:21:18 #623] DEBUG -- : > -A POSTROUTING -o wlan0 -j MASQUERADE
D, [2018-06-08 17:21:18 #623] DEBUG -- : > -A POSTROUTING -o wlan1 -j MASQUERADE
D, [2018-06-08 17:21:18 #623] DEBUG -- : > COMMIT
D, [2018-06-08 17:21:18 #623] DEBUG -- : > # Completed on Fri Jun  8 17:21:18 2018
D, [2018-06-08 17:21:18 #623] DEBUG -- : > # Generated by iptables-save v1.4.21 on Fri Jun  8 17:21:18 2018
D, [2018-06-08 17:21:18 #623] DEBUG -- : > *mangle
D, [2018-06-08 17:21:18 #623] DEBUG -- : > :PREROUTING ACCEPT [0:0]
D, [2018-06-08 17:21:18 #623] DEBUG -- : > :INPUT ACCEPT [0:0]
D, [2018-06-08 17:21:18 #623] DEBUG -- : > :FORWARD ACCEPT [0:0]
D, [2018-06-08 17:21:18 #623] DEBUG -- : > :OUTPUT ACCEPT [0:0]
D, [2018-06-08 17:21:18 #623] DEBUG -- : > :POSTROUTING ACCEPT [0:0]
D, [2018-06-08 17:21:18 #623] DEBUG -- : > :HTTP - [0:0]
D, [2018-06-08 17:21:18 #623] DEBUG -- : > :HTTPS - [0:0]
D, [2018-06-08 17:21:18 #623] DEBUG -- : > COMMIT
D, [2018-06-08 17:21:18 #623] DEBUG -- : > # Completed on Fri Jun  8 17:21:18 2018
D, [2018-06-08 17:21:18 #623] DEBUG -- : > You are now in dual mode
D, [2018-06-08 17:21:19 #623] DEBUG -- : > { "deployment": "ou.mazi", "admin": "Mark Gaved", "title": "Dr", "description": "This is the testing unit for the OU team", "loc": "39.379012, 22.902813", "mode": "dual" }
D, [2018-06-08 17:21:19 #623] DEBUG -- : request: get/admin_network from ip: 127.0.0.1 params: {"splat"=>[], "captures"=>["admin_network"], "index"=>"admin_network"}
D, [2018-06-08 17:21:19 #623] DEBUG -- : $ sh /root/back-end/current.sh -s -p -c -m
D, [2018-06-08 17:21:19 #623] DEBUG -- : > channel 1
D, [2018-06-08 17:21:19 #623] DEBUG -- : > ssid http://ou.mazi
D, [2018-06-08 17:21:19 #623] DEBUG -- : > password -
D, [2018-06-08 17:21:19 #623] DEBUG -- : > mode "dual"
D, [2018-06-08 17:21:19 #623] DEBUG -- : $ sh /root/back-end/antenna.sh -a
D, [2018-06-08 17:21:19 #623] DEBUG -- : > inactive
D, [2018-06-08 17:21:19 #623] DEBUG -- : $ sh /root/back-end/mazi-router.sh -s
D, [2018-06-08 17:21:21 #623] DEBUG -- : > router unavailable
D, [2018-06-08 17:21:21 #623] DEBUG -- : $ sh /root/back-end/current.sh -w
D, [2018-06-08 17:21:21 #623] DEBUG -- : > device Raspberry pi
D, [2018-06-08 17:21:21 #623] DEBUG -- : $ sh /root/back-end/current.sh -d
D, [2018-06-08 17:21:21 #623] DEBUG -- : > domain portal.mazizone.eu
D, [2018-06-08 17:21:36 #623] DEBUG -- : request: put/action from ip: 127.0.0.1 action: reboot
D, [2018-06-08 17:21:36 #623] DEBUG -- : request: get/admin from ip: 127.0.0.1 params: {"splat"=>[], "captures"=>["admin"], "index"=>"admin"}
D, [2018-06-08 17:21:36 #623] DEBUG -- : request: get/admin_dashboard from ip: 127.0.0.1 params: {"splat"=>[], "captures"=>["admin_dashboard"], "index"=>"admin_dashboard"}
D, [2018-06-08 17:21:36 #623] DEBUG -- : $ sh /root/back-end/current.sh -s -p -c -m
D, [2018-06-08 17:21:36 #623] DEBUG -- : > channel 1
D, [2018-06-08 17:21:36 #623] DEBUG -- : > ssid http://ou.mazi
D, [2018-06-08 17:21:36 #623] DEBUG -- : > password -
D, [2018-06-08 17:21:36 #623] DEBUG -- : > mode "dual"
D, [2018-06-08 17:21:36 #623] DEBUG -- : $ sh /root/back-end/mazi-stat.sh -u -t -c -r -s --sd
D, [2018-06-08 17:21:38 #623] DEBUG -- : Restarting
D, [2018-06-08 17:21:38 #633] DEBUG -- : Exiting
D, [2018-06-08 17:21:39 #623] DEBUG -- : > wifi users: 1
D, [2018-06-08 17:21:39 #623] DEBUG -- : > temp: 49.9'C
D, [2018-06-08 17:21:40 #623] DEBUG -- : > cpu: 59.6%
D, [2018-06-08 17:21:40 #623] DEBUG -- : > ram: 75.8%
D, [2018-06-08 17:21:40 #623] DEBUG -- : > SD size: 15.9GB
D, [2018-06-08 17:21:40 #623] DEBUG -- : > expand: No
D, [2018-06-08 17:21:40 #623] DEBUG -- : > storage: 5029MB (72%)
D, [2018-06-08 17:21:42 #623] DEBUG -- : Exiting
D, [2018-06-08 17:22:01 #674] DEBUG -- : Updating Dependencies
D, [2018-06-08 17:22:01 #674] DEBUG -- :   Checking MySQL gem
D, [2018-06-08 17:22:01 #674] DEBUG -- :   Checking sshpass package
D, [2018-06-08 17:22:01 #674] DEBUG -- :   Checking jq package
D, [2018-06-08 17:22:01 #674] DEBUG -- :   Checking i18n gem
D, [2018-06-08 17:22:01 #674] DEBUG -- :   Checking Guestbook version
D, [2018-06-08 17:22:01 #674] DEBUG -- :   Checking Nextcloud version
D, [2018-06-08 17:22:01 #674] DEBUG -- :   Checking sqlite3 package
D, [2018-06-08 17:22:01 #674] DEBUG -- :   Checking rc.local file
D, [2018-06-08 17:22:01 #674] DEBUG -- : delete update lock file
D, [2018-06-08 17:22:01 #674] DEBUG -- : done.
D, [2018-06-08 17:22:21 #674] DEBUG -- : INIT with config: {:general=>{:mode=>"normal"}, :admin=>{:admin_username=>"mazi_admin", :admin_password=>"n0smoking"}, :scripts=>{:backend_scripts_folder=>"/root/back-end/", :enabled_scripts=>["wifiap.sh", "current.sh", "internet.sh", "mazi-app.sh", "mazi-stat.sh", "mazi-router.sh", "mazi-domain.sh", "antenna.sh", "date", "ls"]}, :portal_configuration=>{:title=>"MAZI Zone Portal", :applications_title=>"MAZI Zone", :applications_subtitle=>"Applications", :applications_welcome_text=>"Welcome to the MAZI Zone Applications Portal, please use the links bellow to navigate to the applications offered by this MAZI Zone.", :applications_background_image=>"mazi-background.jpg", :side_panel_color=>"222", :side_panel_active_color=>"080808", :top_panel_color=>"222", :top_panel_active_color=>"080808"}, :sensors=>{:enable=>false}, :camera=>{:enable=>false}, :monitoring=>{:enable=>false, :applications_enable=>false, :hardware_enable=>false, :map=>false}}
D, [2018-06-08 17:22:21 #674] DEBUG -- : Initializing Camera Module
D, [2018-06-08 17:22:21 #674] DEBUG -- : Initializing RPI
D, [2018-06-08 17:22:24 #674] DEBUG -- : request: get/admin_network from ip: 127.0.0.1 params: {"splat"=>[], "captures"=>["admin_network"], "index"=>"admin_network"}
D, [2018-06-08 17:22:24 #674] DEBUG -- : Not authorized
D, [2018-06-08 17:22:37 #674] DEBUG -- : request: get/admin_login from ip: 127.0.0.1 params: {"goto"=>"admin_network", "splat"=>[], "captures"=>["admin_login"], "index"=>"admin_login"}
D, [2018-06-08 17:22:48 #674] DEBUG -- : request: post/admin_login from ip: 127.0.0.1 creds: {"goto"=>"admin_network", "username"=>"mazi_admin", "password"=>"n0smoking"}
D, [2018-06-08 17:22:48 #674] DEBUG -- : valid credential
D, [2018-06-08 17:22:48 #674] DEBUG -- : request: get/admin_network from ip: 127.0.0.1 params: {"splat"=>[], "captures"=>["admin_network"], "index"=>"admin_network"}
D, [2018-06-08 17:22:48 #674] DEBUG -- : $ sh /root/back-end/current.sh -s -p -c -m
D, [2018-06-08 17:22:48 #674] DEBUG -- : > channel 1
D, [2018-06-08 17:22:48 #674] DEBUG -- : > ssid http://ou.mazi
D, [2018-06-08 17:22:48 #674] DEBUG -- : > password -
D, [2018-06-08 17:22:48 #674] DEBUG -- : > mode "dual"
D, [2018-06-08 17:22:48 #674] DEBUG -- : $ sh /root/back-end/antenna.sh -a
D, [2018-06-08 17:22:48 #674] DEBUG -- : > inactive
D, [2018-06-08 17:22:48 #674] DEBUG -- : $ sh /root/back-end/mazi-router.sh -s
D, [2018-06-08 17:22:50 #674] DEBUG -- : > router unavailable
D, [2018-06-08 17:22:50 #674] DEBUG -- : $ sh /root/back-end/current.sh -w
D, [2018-06-08 17:22:50 #674] DEBUG -- : > device Raspberry pi
D, [2018-06-08 17:22:50 #674] DEBUG -- : $ sh /root/back-end/current.sh -d
D, [2018-06-08 17:22:51 #674] DEBUG -- : > domain portal.mazizone.eu
D, [2018-06-08 17:22:51 #674] DEBUG -- : request: post/admin_login from ip: 127.0.0.1 creds: {"goto"=>"admin_network", "username"=>"mazi_admin", "password"=>"n0smoking"}
D, [2018-06-08 17:22:51 #674] DEBUG -- : valid credential
D, [2018-06-08 17:22:51 #674] DEBUG -- : request: get/admin_network from ip: 127.0.0.1 params: {"splat"=>[], "captures"=>["admin_network"], "index"=>"admin_network"}
D, [2018-06-08 17:22:51 #674] DEBUG -- : $ sh /root/back-end/current.sh -s -p -c -m
D, [2018-06-08 17:22:51 #674] DEBUG -- : > channel 1
D, [2018-06-08 17:22:51 #674] DEBUG -- : > ssid http://ou.mazi
D, [2018-06-08 17:22:51 #674] DEBUG -- : > password -
D, [2018-06-08 17:22:51 #674] DEBUG -- : > mode "dual"
D, [2018-06-08 17:22:51 #674] DEBUG -- : $ sh /root/back-end/antenna.sh -a
D, [2018-06-08 17:22:51 #674] DEBUG -- : > inactive
D, [2018-06-08 17:22:51 #674] DEBUG -- : $ sh /root/back-end/mazi-router.sh -s
D, [2018-06-08 17:22:53 #674] DEBUG -- : > router unavailable
D, [2018-06-08 17:22:53 #674] DEBUG -- : $ sh /root/back-end/current.sh -w
D, [2018-06-08 17:22:53 #674] DEBUG -- : > device Raspberry pi
D, [2018-06-08 17:22:53 #674] DEBUG -- : $ sh /root/back-end/current.sh -d
D, [2018-06-08 17:22:53 #674] DEBUG -- : > domain portal.mazizone.eu
D, [2018-06-08 17:31:22 #674] DEBUG -- : request: get/admin_logs from ip: 127.0.0.1 params: {"splat"=>[], "captures"=>["admin_logs"], "index"=>"admin_logs"}
D, [2018-06-08 17:31:38 #674] DEBUG -- : request: get/admin_network from ip: 127.0.0.1 params: {"splat"=>[], "captures"=>["admin_network"], "index"=>"admin_network"}
D, [2018-06-08 17:31:38 #674] DEBUG -- : $ sh /root/back-end/current.sh -s -p -c -m
D, [2018-06-08 17:31:38 #674] DEBUG -- : > channel 1
D, [2018-06-08 17:31:38 #674] DEBUG -- : > ssid http://ou.mazi
D, [2018-06-08 17:31:38 #674] DEBUG -- : > password -
D, [2018-06-08 17:31:38 #674] DEBUG -- : > mode "dual"
D, [2018-06-08 17:31:38 #674] DEBUG -- : $ sh /root/back-end/antenna.sh -a
D, [2018-06-08 17:31:38 #674] DEBUG -- : > inactive
D, [2018-06-08 17:31:38 #674] DEBUG -- : $ sh /root/back-end/mazi-router.sh -s
D, [2018-06-08 17:31:40 #674] DEBUG -- : > router unavailable
D, [2018-06-08 17:31:40 #674] DEBUG -- : $ sh /root/back-end/current.sh -w
D, [2018-06-08 17:31:40 #674] DEBUG -- : > device Raspberry pi
D, [2018-06-08 17:31:40 #674] DEBUG -- : $ sh /root/back-end/current.sh -d
D, [2018-06-08 17:31:40 #674] DEBUG -- : > domain portal.mazizone.eu
D, [2018-06-08 17:31:40 #674] DEBUG -- : request: get/admin_dashboard from ip: 127.0.0.1 params: {"splat"=>[], "captures"=>["admin_dashboard"], "index"=>"admin_dashboard"}
D, [2018-06-08 17:31:40 #674] DEBUG -- : $ sh /root/back-end/current.sh -s -p -c -m
D, [2018-06-08 17:31:40 #674] DEBUG -- : > channel 1
D, [2018-06-08 17:31:40 #674] DEBUG -- : > ssid http://ou.mazi
D, [2018-06-08 17:31:40 #674] DEBUG -- : > password -
D, [2018-06-08 17:31:40 #674] DEBUG -- : > mode "dual"
D, [2018-06-08 17:31:40 #674] DEBUG -- : $ sh /root/back-end/mazi-stat.sh -u -t -c -r -s --sd
D, [2018-06-08 17:31:43 #674] DEBUG -- : > wifi users: 1
D, [2018-06-08 17:31:43 #674] DEBUG -- : > temp: 50.5'C
D, [2018-06-08 17:31:44 #674] DEBUG -- : > cpu: 10.3%
D, [2018-06-08 17:31:44 #674] DEBUG -- : > ram: 60.9%
D, [2018-06-08 17:31:45 #674] DEBUG -- : > SD size: 15.9GB
D, [2018-06-08 17:31:45 #674] DEBUG -- : > expand: No
D, [2018-06-08 17:31:45 #674] DEBUG -- : > storage: 5029MB (72%)
D, [2018-06-08 17:31:48 #674] DEBUG -- : request: get/admin_dashboard from ip: 127.0.0.1 params: {"splat"=>[], "captures"=>["admin_dashboard"], "index"=>"admin_dashboard"}
D, [2018-06-08 17:31:48 #674] DEBUG -- : $ sh /root/back-end/current.sh -s -p -c -m
D, [2018-06-08 17:31:48 #674] DEBUG -- : > channel 1
D, [2018-06-08 17:31:48 #674] DEBUG -- : > ssid http://ou.mazi
D, [2018-06-08 17:31:48 #674] DEBUG -- : > password -
D, [2018-06-08 17:31:48 #674] DEBUG -- : > mode "dual"
D, [2018-06-08 17:31:48 #674] DEBUG -- : $ sh /root/back-end/mazi-stat.sh -u -t -c -r -s --sd
D, [2018-06-08 17:31:51 #674] DEBUG -- : > wifi users: 1
D, [2018-06-08 17:31:51 #674] DEBUG -- : > temp: 51.5'C
D, [2018-06-08 17:31:52 #674] DEBUG -- : > cpu: 1.2%
D, [2018-06-08 17:31:52 #674] DEBUG -- : > ram: 57.6%
D, [2018-06-08 17:31:52 #674] DEBUG -- : > SD size: 15.9GB
D, [2018-06-08 17:31:52 #674] DEBUG -- : > expand: No
D, [2018-06-08 17:31:52 #674] DEBUG -- : > storage: 5029MB (72%)
D, [2018-06-08 17:31:58 #674] DEBUG -- : request: get/admin_settings from ip: 127.0.0.1 params: {"splat"=>[], "captures"=>["admin_settings"], "index"=>"admin_settings"}
D, [2018-06-08 17:32:08 #674] DEBUG -- : request: post/set_date from ip: 127.0.0.1 params: {"date"=>"", "timezone"=>""}
E, [2018-06-08 17:32:08 #674] ERROR -- : undefined method `exec_command' for nil:NilClass
E, [2018-06-08 17:32:08 #674] ERROR -- :   /root/portal/lib/routes/mazi_config.rb:38:in `block in registered'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `[]'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:225:in `context'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220:in `call'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/rack-1.6.5/lib/rack/nulllogger.rb:9:in `call'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/thin-1.7.0/lib/thin/connection.rb:86:in `block in pre_process'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `catch'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `pre_process'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/thin-1.7.0/lib/thin/connection.rb:53:in `process'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/thin-1.7.0/lib/thin/connection.rb:39:in `receive_data'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:194:in `run_machine'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:194:in `run'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/thin-1.7.0/lib/thin/backends/base.rb:73:in `start'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/thin-1.7.0/lib/thin/server.rb:162:in `start'
E, [2018-06-08 17:32:08 #674] ERROR -- :   /var/lib/gems/2.1.0/gems/thin-1.7.0/lib/thin/server.rb:148:in `start'
E, [2018-06-08 17:32:08 #674] ERROR -- :   mazi_portal_server.rb:171:in `'
D, [2018-06-08 17:32:09 #674] DEBUG -- : request: get/admin_settings from ip: 127.0.0.1 params: {"splat"=>[], "captures"=>["admin_settings"], "index"=>"admin_settings"}
D, [2018-06-08 17:32:27 #674] DEBUG -- : request: post/set_date from ip: 127.0.0.1 params: {"date"=>"2018/06/08 17:32", "timezone"=>"Europe/London"}
D, [2018-06-08 17:32:29 #674] DEBUG -- : $  date -s '2018/06/08 17:32'
D, [2018-06-08 17:32:00 #674] DEBUG -- : > Fri  8 Jun 17:32:00 BST 2018
D, [2018-06-08 17:32:00 #674] DEBUG -- : request: get/admin_settings from ip: 127.0.0.1 params: {"splat"=>[], "captures"=>["admin_settings"], "index"=>"admin_settings"}
D, [2018-06-08 17:35:37 #674] DEBUG -- : request: get/admin_documentation from ip: 127.0.0.1 params: {"splat"=>[], "captures"=>["admin_documentation"], "index"=>"admin_documentation"}
D, [2018-06-08 17:35:40 #674] DEBUG -- : request: get/admin_logs from ip: 127.0.0.1 params: {"splat"=>[], "captures"=>["admin_logs"], "index"=>"admin_logs"}

**Comment by mgaved** [comment]
Solved - the upate pop-up window doesn't work in Internet Explorer 7, seems to work in Chrome. When I try to do an update in Chrome then the correct "Update" window appears.

However when the MAZIzone reboots as v2.5, the Raspberry Pi doesn't broadcast its SSID so I can't connect to it. I will investigate and raise another issue.

**Comment by haniavis** [comment]
Hi, this could be a caching problem or incompatibility with IE 7. Please try to update your browser or use a different one.

In the new update process since 2.4.6, you have to wait for the SSID to appear and this is the sign that the update process finished successfully. But you have to wait for it, sometimes more than 5 min.

Do you still have troubles to connect to this MAZI Zone? Do you still need to update this MAZI Zone, or it was just a test? In that case, we can close this issue.
