### ISSUE TITLE
recovering/resetting administrator password

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#11]
Hi, I have a MAZI Zone 1.5-3 and I cannot login as administrator while before I could. I don't remember if I changed the admin password while playing with different features of the admin panel (I think not).

But in any case what can I do now? (I guess this will be a typical situation)

Since I can ssh to the RPi perhaps there should be a script to reset the password from the command line? And in the future perhaps add the option for password recovery through e-mail?

**Comment by haniavis** [comment]
Since we could have offline deployments (not connected to the Internet) we can not add the option for password recovery through e-mail.

For now, we will add a script to reset the Portal password from the command line.

**Comment by panosnethood** [comment]
I was thinking about this and perhaps it would make sense to keep "synchronized" the admin password and the pi user's password through ssh. And if one forgets the single password for both, then the best solution is a "hard reset" through deleting for example a certain file from the SD card. If someone has access to the card we could assume that is the right person anyway.

**Comment by haniavis** [comment]
Integrated in v1.8.5

**Comment by panosnethood** [comment]
what is the command to reset the password?

**Comment by crickxson** [comment]
Hello here.
Thanks to have integrated it in v1.8.5.
But what is the command to reset the password?

**Comment by panosnethood** [comment]
Hello!

Check here: https://github.com/mazi-project/guides/wiki/Troubleshooting

You need to access your Raspberry Pi through ssh: https://github.com/mazi-project/guides/wiki/Command-line-administration
