### ISSUE TITLE
Dual mode: Internet access is restricted

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#110]
I have a MAZI Zone running on dual mode, which I updated from 2.4.6 to 2.5 and  now it seems that some ports are closed (I cannot check my e-mail through my desktop application, thunderbird, for example).

Ideally, this should be an option for the administrator to use and I would have unrestricted access as the default behaviour especially since this was the way the "dual" mode was working until now.

**Comment by haniavis** [comment]
Hi,

thanks for reporting, we are working on allowing all ports in dual mode and it will be fixed asap.

**Comment by panosnethood** [comment]
Thanks! And btw, this is more important than I thought since many MAZI applications run on different ports and there are not accessible in dual mode.

**Comment by haniavis** [comment]
You can already update to v2.5.1 where ports for all MAZI applications (Etherpad, Guestbook, Internet Archive) are enabled.

We are working on a new version, enabling all other ports.

**Comment by panosnethood** [comment]
This bug caused some inconvenience for me because I had a MAZI Zone set in a public space for offering Internet access and after the update this problem appeared and today in a big event I couldn't offer Internet access as planned (I didn't want to explain that not all ports are open etc). And I couldn't also roll back to the previous situation when everything was working exactly as I wanted.

Perhaps we should "warn" people when an update is not up to an "official" release and then the admins should select it on their own responsibility. 

Ideally, we should offer two update options: "Update until the latest official release" & "Update until the latest commit (with your own responsibility)" or something like this.

**Comment by haniavis** [comment]
Hi,
we are working on this solution where we will provide 2 update channels, the "Stable" and the "Development". And the user will choose if he/she wants to have the latest development version or the latest stable one.

**Comment by haniavis** [comment]
This is now fixed in v2.5.2, check changes [here](https://github.com/mazi-project/guides/wiki/Version-History)

**Comment by haniavis** [comment]
Hi,
all ports in v2.5.2 are open. 

Could you check your image since you were experimenting with different things lately and you might have misconfigured something?

**Comment by haniavis** [comment]
Update:
In v2.5.2 image all ports are open. 

When updating from v2.4.6 to v.2.5.2 you will again correctly see all ports open. But when updating from 2.5.1 to 2.5.2 ports will be still closed. We are working on a fix to v2.5.3.

**Comment by haniavis** [comment]
Could you check now, updating your v2.5.2 to v2.5.3 to see if ports are open?

**Comment by panosnethood** [comment]
Yes, it works now. Thanks! Only problem that the update overwrote my splash.html page and now I have to do it from scratch!
