### ISSUE TITLE
in dual mode, custom URL not updated in splash page

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#118]
Hi,

In a fresh 2.5.3 install, I changed to dual mode and set a custom URL, but the splash page redirects to the original (portal.mazizone.eu). Changing back to offline mode, the splash page is correctly updated.

Not sure if it is important, but although it was dual mode, the MAZI Zone was not actually connected to the Internet.

**Comment by haniavis** [comment]
fixed in v2.5.6
