### ISSUE TITLE
What ports do I need to keep open on an intranet to access the MAZI demo server?

### ISSUE THREAD

**Issue by mgaved** [mazi-project/portal#121]
I am inside a university network and access to the MAZI demo server has stopped working (http://demo.mazizone.eu).  I suspect it is because my university security has closed access to some ports .

What ports do I need my university to allow me access to in order to visit the demo,mazizone server and use all the services? 
- 4567
- 9001
- 80
- any others? 

Thanks!
Mark

**Comment by mavridis92** [comment]
The ports which we use are the following

-  4567 Portal

-  9001 Etherpad 

-  8081 Guestbook 

-  9091 Interview

**Comment by mgaved** [comment]
Many thanks, I can't access it from my university and I am pretty sure it is a port issue (I can connect successfully from my home network in the evenings)
