### ISSUE TITLE
Not getting back to admin dashboard after making wordpress splashpage

### ISSUE THREAD

**Issue by eclcg** [mazi-project/portal#126]
#After flipping the switch to make my wordpress the splash page, there is no way of getting back to the admin dashbord. Every adress such as: 
http://10.0.0.1/admin
http://portal.mazizone.eu/admin 
just redirect me back to the wordpress site. I can get into the backend of the wp but not of the entire MAZI.

**Comment by haniavis** [comment]
If you change the splash page you can access the admin interface again through portal.mazizone.eu/admin as you always do. 

Alternatively you can always use 10.0.0.1:4567/admin or local.mazizone.eu:4567/admin regardless of your splash page or domain.
