### ISSUE TITLE
network configurations (password) get lost after a reboot 

### ISSUE THREAD

**Issue by dominic-herzog** [mazi-project/portal#127]
I have a MAZI zone v2.5.3 and would like to use mazizone in dual mode (together with an Edimax EW-7811UTC: DualBand USB Adapter (USB 3.0) )

My issue is that most network configurations get lost after a reboot.

1) the SSID stays but the password is droped and not required after rebooting
2) the USB1 WiFi infromation gets lost

I have also tried to add the information manually  to the hostapd.conf file, and to add some lines to the rc.local files (as explained in the "start everything at boot" on http://nitlab.inf.uth.gr/mazi-guides/accessPoint.html#setup-a-wi-fi-access-point-in-the-raspberry)

Does anyone have any idea how this can be solved and the WiFi is still password protected (and the raspberry pi connects automatically to the other hotspot) after a restart?

Thank you for any hints on this. Tell me if you need some more information.

before restart:
![before restart](https://user-images.githubusercontent.com/16637363/43676197-a3da32f4-97ec-11e8-8415-41bfadd13616.png)

after restart:
![after restart](https://user-images.githubusercontent.com/16637363/43676199-b27f00aa-97ec-11e8-9031-c05914b30b7e.png)

rc.local:
![screenshot rc_local](https://user-images.githubusercontent.com/16637363/43676201-bb9b9aea-97ec-11e8-8296-7574cd4f24ae.png)

**Comment by panosnethood** [comment]
Thanks Dominic! I have reproduced this after updating to the latest stable version.

**Comment by haniavis** [comment]
Hi

we are working on this and it will be fixed in the next release

**Comment by juliobrome** [comment]
Hello, same problem in my zone.

**Comment by panosnethood** [comment]
Just did an update on the "development" thread and there was a password added to my mazizone! Is this part of the correction of this bug?

**Comment by haniavis** [comment]
Yes this is "part" of the solution of this bug and we are working on it in the development branch, as you see.

The password is most probably mazizone.

**Comment by haniavis** [comment]
This is now fixed in v2.5.5
