### ISSUE TITLE
upgrade failed

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#13]
Hi, I have upgraded from version 1.5.3 to 1.6 according to the instructions and I get this error "NameError at /admin_dashboard
undefined local variable or method `version' for #<MaziApp:0x22f5198>"

In the installed 1.5.3 I had changed the text and URLs of some applications (etherpad, nextcloud) and nothing more I think.

**Comment by ardadouk** [comment]
Hi Panos,

have you restarted the portal after the upgrade?

If you haven't, please do so with:
service mazi-portal restart

if this fixes the issue, I will add this command to the list of commands you need to execute in order to upgrade.

**Comment by panosnethood** [comment]
I didn't check this because I was travelling and now I am not sure where I put that SD card. I close the issue.
