### ISSUE TITLE
limit of DHCP leases reached!

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#130]
Hi,

I am happy to inform you that a group in Zurich managed to reach the limit of the DHCP leases (~190) during a big festival.

If I understood correctly this was not the number of concurrent connections, but the number of all connections through the day that an engineer from the group informed me that it is somehow limited (?), something that is not difficult to address (he said that we need to define a larger subnet, or something like this, I didn't understand very well, he used many unknown words :-)).

Anyway. Depending on your answer I can ask more details on what exactly was their experience and the proposed solution.

**Comment by mgaved** [comment]
I'd love to also know the answer and congratulate you on the positive problem!

**Comment by mgaved** [comment]
I've added a guide in the Wiki to managing this issue: [https://github.com/mazi-project/guides/wiki/Changing-number-of-users-that-can-connect-to-a-MAZIzone](url)
