### ISSUE TITLE
explanation of "Auto Expand Comment" in Guestbook web admin tool?

### ISSUE THREAD

**Issue by mgaved** [mazi-project/portal#131]
In the guestbook administration tool, there are a number of settings (it's great to have these in a web page!).

Can you explain what the "Auto Expand Comment" option does (True/False options)

"Auto Expand Comment
You can use the button bellow to change the auto expand comment feature. The current value is: false"

Next to this option is an Info icon. When you roll over this, it says 
"You can use this to change the auto expand comment feature"

(1) Could somebody explain what the "Auto Expand Comment" does? thanks!
(2) Could we change the guidance text to be more descriptive?
(3) Could we change the text on the roll-over Info icon as this duplicates the existing explanation: use it to provide a further explanation.
(4) small typo: change "bellow" to "below"

many thanks!

**Comment by panosnethood** [comment]
Yes, when true, the comment area is visible without having to click on the small box including the motivation string (it is "expanded automatically"). You can try out :-)

Then I agree that it is not easy to understand and suggestions for better ways to describe it are more than welcome.

**Comment by mgaved** [comment]
Thanks! I'll try, and put up some suggestions of better text. Thanks for swift response!
