### ISSUE TITLE
Adding new languages?

### ISSUE THREAD

**Issue by mgaved** [mazi-project/portal#132]
It's great that MAZI is now part of the Translate Wiki project. https://translatewiki.net/wiki/Translating:MAZI_Toolkit

How do I add the languages that are complete to the v2.5.3 MAZI toolkit interface? At the moment, it looks like I can choose between English and Greek, but I see (for example) that French has a 100% translation.

How can I add French (or other languages within the Translate Wiki MAZI system) to my MAZIzone?

thanks!

**Comment by haniavis** [comment]
This is a task for the development team, to visualize the integrated language translations and then users will be able to select their language from the Portal. We are in the process of making this happen soon, waiting also for more languages to be pushed from the Translatewiki platform.

We will keep you updated.

**Comment by mgaved** [comment]
Thanks! I appreciate the work of the development team! 

I would be happy at the moment to be able to pull in the languages that have 100% translation (e.g. Arabic, French). in Creeknet we have contacts with French speakers, so we don't have the need to wait until 'more languages' are ready, (not sure how many you are waiting for), adding French would be good.

Good luck with the development work!

**Comment by haniavis** [comment]
we understand your request and working on the integration of all 100% translated languages.

Thanks for the feedback
