### ISSUE TITLE
Display code for icon by default in Application panel

### ISSUE THREAD

**Issue by mgaved** [mazi-project/portal#133]
(1) In the Administrator panel, when I go to Applications, I can see which Applications are installed. I can change the title and the introductory text for appearing in the Portal for each application. However, when I make a text change, it loses the icon. 

 Can you alter the edit function so it doesn't lose the Icon when I make another change?

(2) Also, by default, the first time I go to edit any of the icons' texts (or colour), the Icon is defined as "Icon" and not the name of the Awesome Font icon. This means if I like one (e.g. the cloud) and wish to copy the reference and use it in another application, I can't: I have to go online to find its code name. Suggestion: by default always show the code name of each icon rather than "Icon".

thanks!

**Comment by haniavis** [comment]
This is now fixed in v2.5.5
