### ISSUE TITLE
Etherpad running slow in v2.5.3 stable branch

### ISSUE THREAD

**Issue by mgaved** [mazi-project/portal#135]
Etherpad takes approximately 30 seconds to go from clicking on the link to loading a pad. I’ve only recently experienced this. I am using v2.5.3 stable branch, I am not sure it is a particular problem with this MAZI release or more generally.

Does anybody know what the issue might be? 

This is really difficult when promoting the value of etherpad to potential users and I am hoping there’s a speed-up solution. I am not sure why I am now experiencing this issue

Is anybody else experiencing this issue?

I came across this old etherpad git hub issues question https://github.com/ether/etherpad-lite/issues/224

Might it be that our etherpad is looking up something and there’s a config change that will help? (e.g. “setting proxy_buffering off”)

**Comment by mgaved** [comment]
Thanks Panos. I'd agree, it seems to happen the first time a user goes to etherpad. I wonder if that means its an issue on the user's browser, or if there's an overhead in that first download? I will have a bit of an explore but suggestions from colleagues welcomed.

**Comment by haniavis** [comment]
Etherpad needs some time when booting your raspberry, so if you turn on your mazizone and immediately try to access it, you might get an error. Try to give it some time after booting.

In addition, I have also experienced some issues like what you are describing, etherpad being slow or crashing which you can fix with a reboot. 

Our stretch version will feature the updated Etherpad version (1.6.6) which uses the updated nodejs and will be more stable.
