### ISSUE TITLE
typo in Admin interface: Applications: Edit Application Instance

### ISSUE THREAD

**Issue by mgaved** [mazi-project/portal#137]
(v2.5.3 stable branch)
In the Admin interface for the MAZI toolkit, if you go to Applications, and edit the appearance of an Application ('Edit Application Instance') you are given a pop up window.

There is a drop down box for the different colours that can be chosen.

Spelling mistake: "navi" should be "navy" in English (dark blue, or 'navy blue')

**Comment by haniavis** [comment]
This is now fixed in v2.5.5.
Thanks for reporting
