### ISSUE TITLE
re-appearance

### ISSUE THREAD

**Issue by deckspace** [mazi-project/portal#14]
After  following upgrade from 1.6 to 1.6.5 (and perhaps from 1.5.4) all appearance settings are lost 

'You can use the tools bellow to take a snapshot of the current configuration of this Mazizone. This includes everything (network configurations, applications, application instances, notifications, visual configurations, etc).'

should we be saving appearance settings, somewhere? how can we do this?

**Comment by haniavis** [comment]
As soon as you followed the updated process you should have the file /etc/mazi/config.yml.bu which is the settings of your old version.

So can copy your old appearance settings from the file /etc/mazi/config.yml.bu to the file /etc/mazi/config.yml

I hope this helps.

**Comment by panosnethood** [comment]
Perhaps to add the above as an optional step in the upgrade process?

**Comment by haniavis** [comment]
Since version 1.6.5, the update process automatically recovers your old appearance settings.

Please check and comment if this doesn't happen.

**Comment by deckspace** [comment]
on upgrading to V1.7 we lost the custom appearance settings. Other settings were unaffected.

**Comment by panosnethood** [comment]
I successfully updated from v1.6.5 and custom appearance settings were preserved. Perhaps the initial version was older than 1.6.5?

**Comment by deckspace** [comment]
I think it was an upgrade from v1.6

**Comment by panosnethood** [comment]
Hmm, I would propose to "reset" our base version to be 1.7 and re-open this and other related issues if updates do not work as expected from this version (1.7) as a starting point.
