### ISSUE TITLE
Capture missing comments text in snapshot (export) function for Guestbook

### ISSUE THREAD

**Issue by mgaved** [mazi-project/portal#141]
(v2.5.5 MAZI) In the Admin interface , Export option, it is possible to to export posts from Guestbook. However when I have done this for posts that have comments, I can't see where the text of comments associated with a post are held? 

Are these being captured in the snapshot export to JSON format? if so, where? thanks for your help!

**Comment by mgaved** [comment]
Thanks - can I also ask what some of the field titles mean? 
"__v" what is this?
"dataset" - this always seems to be "default" - what else can it be?
"device" - this always seems to be "FALSE"
"files/0/_id/$oid" - what is this?
"location/0" - what is this? 
"title" - this is always FALSE - is it a hidden field that's not been activated?

thanks for the help!

**Comment by haniavis** [comment]
This is now solved since v2.6.
