### ISSUE TITLE
Networking control - 2.5.6

### ISSUE THREAD

**Issue by deckspace** [mazi-project/portal#142]
Hiya I am trying to keep up to date with Mazi and have experienced oddness with recent versions, certainly with V 2.5.6. To begin with there was no USB -wifi network configurator in the network section of admin portal. After a reboot this reappeared ; can no longer switch into Online mode (didn't this get fixed early in V2? ) and over all each selection made in the interface throws up a busy panel even if the link responds immediately. The nodog splash html is still resetting to previous grey one rather than the much improved version.. where did we go wrong?

**Comment by panosnethood** [comment]
Hi James, I have been using 2.5.6 for quite some time and I didn't experience any of this. Did you update from an older version (which?) or started from 2.5.5?

**Comment by deckspace** [comment]
This is a mazi which we have been working on since last trip to Volos , I didn't log when it got last fresh start.  I have another which seems to work more as expected.. using that to practice back up to usb, see other issue...!

**Comment by haniavis** [comment]
This seems to be a css caching problem. 

Did you try to refresh or try from a different browser?

**Comment by deckspace** [comment]
Well it will be a lot easier to refresh if we can backup the existing work
safely. Looks like at last this will be possible so a workflow can be
illustrated and tested that includes recovery.

**Comment by ardadouk** [comment]
Hi James,

what Harris means with refresh is ctr-R on your browser not refreshing the image on the raspberry.
