### ISSUE TITLE
Backup to USB drive

### ISSUE THREAD

**Issue by deckspace** [mazi-project/portal#143]
Very pleased to see th e backup to USB option, thanks!

I set off a back up of a middle sized 32gb based mazi four hours ago, one which had about 10gb of data on it.. how long should it take?.. still running zip and a usb storage process - just viewing top.

**Comment by haniavis** [comment]
So we need some feedback on that. How did it go?

We don't know exactly how much time it needs for backing up each different mazizone, it depends on your data, your SD card, your USB disk etc.

In our tests, we backed up 8gb cards and it needed around 20min for the whole process.

**Comment by deckspace** [comment]
Well the process created a file but it's a file that needs uploading to an
other Mazi and checking out.  Will try that out . As for how long it took
no idea seemed to be hours but perhaps I was being overly cautious.. in the
shell it possible to show progress of a process can't we at least indicate
it's still running or has completed to give some reassurance?

**Comment by ardadouk** [comment]
It has a popup with a work in progress message and a spinning icon.
Didn't this work for you?
Also, this is a blocking process, so you should not be able to use the 
portal during the backup procedure for obvious reasons.
