### ISSUE TITLE
setup mazizone

### ISSUE THREAD

**Issue by deckspace** [mazi-project/portal#15]
We installed V1.6.5 and restarted which triggered the new setup panel requested we set a password, date and essid.. despite several attempts to set the password we were unable to satisfy the request and therefore couldn't complete the form and begin using the mazizone. 

Entering password mazizone worked on one occasion. will upgrade another installation today and track the result in more detail.

using firefox browser

**Comment by haniavis** [comment]
Since v1.6.5 the password "1234" is not permitted. There are alerts that appear if you try to set the password to "1234".

You will manage to pass through the setup panel (password, datetime, essid), unless you set the password to "1234".

**Comment by deckspace** [comment]
We have now been through the setup process a couple more times and think I have identified the issue.
in all cases we had just upgraded from an older version with our password. ie not 1234. When asked for a new password during setup, we entered our password but it was rejected. entering a different password to the one previously used, works just fine.

**Comment by haniavis** [comment]
The only restriction is that you can not have the password 1234. There is no check for a previously used password.

In any case there are alert messages appearing informing you about the reason your password was rejected, could you tell us which messages you see?

**Comment by panosnethood** [comment]
Is this still a valid issue? Perhaps it is the same problem as with custom appearance settings (#14), that is the initial version from which multiple updates were attempted was an older one?

**Comment by haniavis** [comment]
I suppose this can be closed now.
