### ISSUE TITLE
undesirable behaviour in online mode when offline

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#150]
A MAZI adopter noticed that when a MAZI Zone is set to "online" mode while the Raspberry Pi is actually offline the captive portal does not behave as expected.

Is it possible to detect this situation and use the offline mode always when the Raspberry Pi is offline?

**Comment by mavridis92** [comment]
Thanks for your feedback.

It seems that the captive portal service does not respond properly to this case.
We will change the networking section, preventing the online option when the Toolkit has no internet access, providing the appropriate message to the administrator.
For example: 
Please connect your Toolkit to the internet to enjoy the online mode.

**Comment by panosnethood** [comment]
Great, thanks! For later perhaps, it would be nice if the online mode is de-activated automatically when a Raspberry Pi loses Internet connectivity, since this could happen later, after the initial configuration, and even without the user knowing about it.

**Comment by panosnethood** [comment]
Thanks for fixing (partially) this issue. What is still not working is if I have configured my mazizone to "online" because it was connected to the Internet, it does not detect if Internet connection is lost for some reason.

So, in this case it stays online while offline, and the behaviour is not as expected.

I guess this would need a script running always when online to detect if there is indeed internet connectivity. If this wouldn't harm performance I think it is important.

**Comment by panosnethood** [comment]
OK, I added a note on this in the "Networking" section of the "Admin panel" guidelines and also the "Splash page", linking to this issue for more information.
