### ISSUE TITLE
suggestion: Guestbook to show name of current background image

### ISSUE THREAD

**Issue by mgaved** [mazi-project/portal#154]
Hi - this also raised 07 Feb 2018 here: 
https://github.com/mazi-project/guestbook/issues/19

When I upload an image, the Guestbook admin interface doesn't record it, so the only way I can see if an image has been uploaded successfully is to go to the user view and check. See below screenshot for an example where I have uploaded a custom background image that works successfully, but after the action I do not get a positive-feedback in the admin interface to acknowledge a successful upload by e.g. showing the name of the current background image.

Suggestion: in the admin interface, indicate the current background image name, e.g. "foo.jpg" . 

Many thanks!

![background-image-selected-no-confirmation](https://user-images.githubusercontent.com/18211485/48634734-34946a80-e9be-11e8-82e0-3e0ae757c8ee.jpg)

**Comment by haniavis** [comment]
Hi, thanks for reporting this.

Since v3, the current image is shown in the Guestbook admin.
