### ISSUE TITLE
Etherpad error

### ISSUE THREAD

**Issue by juliobrome** [mazi-project/portal#156]
Hello, i work with my stydents in Etherpad (mazi 2.6) for the moment, but we have an error, more on mobile and mac os computers than PC, but there's a lot of mac... So they experiment an error "an error occur, please make ctrl +5... Or call your administrator"on the pad and they can't write on it and the letters reverse...Sometimes refreshing solve the problem but its absolutely not sure and a lot of them let me alone with my mazi... Can you solve this ? Maybe someone else have the same error ? Ps:i have 3 sd card for 3 diferents projects and the same error

**Comment by panosnethood** [comment]
tell them to try a different browser perhaps? I think I had the same issue and it was solved like this.

**Comment by panosnethood** [comment]
also make sure they have exited the default pop-up window that mac launches ....

**Comment by juliobrome** [comment]
We try safari, firefox and chrome, same error

**Comment by juliobrome** [comment]
Are you in paris sunday ? At the Amicale des telecoms in gaite lyrique ?

**Comment by panosnethood** [comment]
Yes :-) I will talk at this panel: https://gaite-lyrique.net/en/event/cultivons-des-reseaux-et-elevons-des-chatons

**Comment by juliobrome** [comment]
Me too ! I talk in this panel just after you :))) :https://gaite-lyrique.net/evenement/lamicale-des-telecoms

**Comment by juliobrome** [comment]
So we can talk around a glass ;)

**Comment by haniavis** [comment]
Hi, this is a known error in etherpad, see https://github.com/ether/etherpad-lite/issues/2107, https://github.com/ether/etherpad-lite/issues/2234 and https://github.com/ether/etherpad-lite/issues/3098.

In my understanding it is a bug of one of the libraries etherpad uses for character encoding. There is a way to recover your pads if needed, check the links I sent.

v3 of the toolkit (will be released soon) uses the latest etherpad version which I hope solves these issues.

**Comment by juliobrome** [comment]
ok i don't loose my pads, just experiment difficulties to work with etherpad in these conditions, so i hope V3 solve issues too !
Thanks

**Comment by juliobrome** [comment]
Thank you for all. 
@panos, i look to etherbox... its a Constant work ! I know them of course i worked with them :)))) i never try etherbox !! So this week i test it 
Thanks again and see you later

**Comment by panosnethood** [comment]
It is a funny place to chat about this :-), but check also this project that focuses more on creating meta-data out of collective writing processes: http://peerproduction.net/issues/issue-11-city/peer-reviewed-papers/the-case-of-teixidora-net-in-barcelona/
