### ISSUE TITLE
nextcloud

### ISSUE THREAD

**Issue by deckspace** [mazi-project/portal#16]
Trying again to add a user account in nextcloud which prompts for a password (mazizone) that we don't have or is not recognised. We are logged in to the mazizone as admin and can use the default nextcloud admin account to set up new directories and sharepoints.. 

please advise

**Comment by haniavis** [comment]
this is an issue of the nextcloud application itself. It seems that you cannot use a common password for your new user and there is no alert for that.

You can disable this, in Admin additional settings at the bottom and set the password strength of your preference.

Check [here](https://github.com/nextcloud/server/issues/2289)
and [here ](https://help.nextcloud.com/t/creating-user-does-not-work/6134/3)

**Comment by panosnethood** [comment]
I have the same problem as James no matter how strong the user password is set. It seems that the problem is different than those nextcloud issues. When a new user is created there is a request to verify the admin's password, and "mazizone" does not work.

**Comment by panosnethood** [comment]
In the latest version, 1.7, I could create a new user without a problem. So, I guess this is resolved?
