### ISSUE TITLE
USB stick not recognized in Snapshot panel

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#162]
I have been trying since many months to get my USB stick recognized. I even bought a new one.

I am trying now again with v3.0.1 with firefox & chrome on ubuntu 18.04 with different USB sticks of various types (e.g., a Transcend and a Gigastone of 16GB) and no success.

Any advice on this? Can you try it with ubuntu to make sure if it is something I am doing wrong or a problem with the implementation?

**Comment by haniavis** [comment]
Hi, this is not related to your pc or operating system. It is the raspberry that doesn't recognize and mount your USB stick.
What is the format of your USB stick?

Can you do a `lsusb` command after you connect your USB stick and check if you can see it in the output?

**Comment by panosnethood** [comment]
OK! This was stupid of me, sorry. I was putting the USB drive on my laptop, not the raspberry Pi :-)

**Comment by panosnethood** [comment]
Btw, while I am doing the back-up, it is not clear to me if I can close the browser window. I think it would be nice to include this information in the message. "The back-up process might take some time, but you can freely close your browser" or something like this.

**Comment by haniavis** [comment]
There is a spinning cycle appearing during the backup procedure and this procedure blocks the portal, so you can not interact with the portal while the backup is running.

**Comment by panosnethood** [comment]
The question is what happens if I close the browser. Will the back-up finish or I should keep my browser open as long as it takes? Given that it seems to take many hours this might be an issue.

**Comment by haniavis** [comment]
You can close your browser, the backup will continue running.

**Comment by panosnethood** [comment]
This is what I mean, it would be nice to inform people that they can close their browser in this pop-up window
