### ISSUE TITLE
In Admin->Applications rename "Splash page" to "Home page"

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#163]
Since the introduction of nodogsplash's splash page we should have a different name of what we were previously calling "splash page", in fact that the "home page", which now appears after the new splash page.

This appears in the Applications menu, the possibility to set an application as "Splash page" and it can be very confusing, especially in the guidelines.

**Comment by haniavis** [comment]
this is now fixed in v3.0.2

Thanks for reporting
