### ISSUE TITLE
admin panel: start/stop applications info missing

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#19]
The info button at the "Installed Applications" panel does not work (it would be useful to explain that those applications cannot be started/stopped because they are integrated in the apache)

**Comment by haniavis** [comment]
This is not a button but you can hover the mouse over it, in order to display the message.

We could have a popup appearing at a later version.

**Comment by panosnethood** [comment]
Ah, OK. I didn't see the hover. Perhaps the message could be also improved to explain why there is no point to start/stop certain applications.

**Comment by panosnethood** [comment]
It is also confusing that in other places the same icon is a button with text appearing below. I think it is important to be consistent on how the user interface works ...

**Comment by haniavis** [comment]
This is now a button since v1.7

**Comment by panosnethood** [comment]
OK, but it would be nice to have the same behaviour as in the "Networking" settings for example, instead of a pop-up window.
