### ISSUE TITLE
Main Interface

### ISSUE THREAD

**Issue by deckspace** [mazi-project/portal#2]
we desperately need to manage the date settings of the PI. so the interface should display the current time and offer easy update (sync to another PC)  and date/time edit tools.

We need to be able to update the admin account with secure password

The guides need to be on the public view of the interface not in the admin section alone.

reduce clutter in the UI - consolidate all the menu options into one list. we don't need a top panel a side panel and a bottom panel as this reduces available screen on a smart phone to almost nothing. nice to able to chose which panel to use.

Seeking a consistent user interface language - easily recognisable icon for actions to edit, save, import and export.. elements , not a jumble of different techniques. 

We need to able to save current configuration to a local configuration library, usb drive or network storage (iscsi, ftp, samba) however these files need to be named well and easily distinguishable one from another. Then  selected from a configuration library for use at another time.

**Comment by haniavis** [comment]
Thanks for all your suggestions.

Most of them are included in the v1.5.2. 

(Please try to add more specific issues as they are easier to handle)
