### ISSUE TITLE
Adding multiple initial URLs through the admin panel

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#22]
Since MAZI Zones are run in very contextualized locations I think it is important for the admin to set a custom "entry" URL that is characteristic of the situation, non standard (demonstrating the additional power to create your own URLs in a local networks), and easy to type (especially in events where people are busy and use their smartphones to join a MAZI Zone this is very important).

To avoid complexity this custom URL could be forwarded to the original portal.mazizone.eu, as it is done anyway.

So, since it is already possible to do this administrator task (by editing the file /etc/hosts) it would be nice to include this configuration option in the "Networking" admin panel.

**Comment by haniavis** [comment]
Integrated in v1.8.5
