### ISSUE TITLE
update from 1.6.5 -> 1.7: links on top bar lost

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#24]
After the update from 1.6.5 to 1.7 I cannot see any link/text on the top bar, except from the label on the left.

**Comment by deckspace** [comment]
Why is there a link to Mazizone.eu on the top bar that will fail if in offline mode? 

Can I suggest that instead the Mazi logo in top right that when clicked resolves to a local page that surmises vital info from mazizone.eu including credits and link to mazizone.eu for those in 'Dual mode'. Then in the top left, the 3 bar hamburger which can be expanded for the menu in both active portal and admin modes. 

Please also add the Admin login option into this menu.

**Comment by ardadouk** [comment]
Is this still an issue?
If yes, can you give us some more info. 
This happens on Admin Panel, on the Portal or on both?
Have you tried to refresh the page with ctr+shift+R so that js/css is not the cached ones.
Please hit F12 and send us the output of the console tab.

**Comment by panosnethood** [comment]
It happened twice to me but I cannot easily reproduce. I have to install again 1.6.5. Refreshing the js/css is a good tip anyway that we should include in the guidelines.

**Comment by panosnethood** [comment]
good point by james. I will prepare a local default "about" page with wordpress that could be included and used in the top bar ...

**Comment by panosnethood** [comment]
So, here is a first example: http://nethood.org/mazi/templates/mazitoolkitwordpresstemplate.wordpress.2017-05-27.xml

It includes two "about" pages. One for the MAZI project, http://local.mazizone.eu/wordpress/index.php/mazi-project/, and one for the specific MAZI Zone, http://local.mazizone.eu/wordpress/index.php/about/

I have also included the corresponding text here to make it easier to edit it collaboratively:
http://demo.mazizone.eu:9001/p/toolkit-wordpress-text

What do you think?

**Comment by haniavis** [comment]
Why not integrating these pages in the core portal instead of having them in the wordpress?

I think we need just the one for the specific Mazizone to be editable. right? This could be edited from the admin portal.

**Comment by panosnethood** [comment]
wordpress import/export does not seem to work very well. We need to explore this further and in any case the original issue is not relevant anymore. I will do some research and create a new issue regarding wordpress integration ...
