### ISSUE TITLE
admin dashboard

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#26]
In version 1.7 the boxes of the admin dashboard are not correctly aligned (there is a gap at the second row at the left column).

It would be also nice if every box was "clickable" as if the user has clicked on the symbol on the top right corner.

And in the case of the "version" box the possibility to check for updates through that box should be also included.

Finally, the date on the admin panel is one hour before the one shown in the user portal (I guess because of a difference in the timezone).

**Comment by ardadouk** [comment]
Can't find a way to reproduce the 'not correct alignment' issue, can you make sure it loads the correct css/js and not a cached one, by reloading ctr+shift+R.
If this persists, can you send me a photo with the problem so I can see what goes wrong.

**Comment by panosnethood** [comment]
I guess you are right because the issue got resolved by itself. We should add the reloading in the guidelines for the update process.
