### ISSUE TITLE
preconfigured snapshots including default

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#27]
It would be useful to have a few predefined snapshots with characteristic names (file sharing, guestbook, etc) and most importantly include the "default" snapshot.

I tried to load a previously exported snapshot and now I cannot get back to the default one.

**Comment by panosnethood** [comment]
Here is a first example of the "workshop" snapshot (and please include also the "default" snapshot):
http://nethood.org/mazi/templates/workshop-snapshot.zip

The next days I will prepare a few more and in the future it would be nice to have a "gallery" on the main web site.

**Comment by panosnethood** [comment]
It would be important in the snapshots to include the actual background photo chosen in the portal page

**Comment by haniavis** [comment]
Integrated in v1.8.5
