### ISSUE TITLE
possability to have wordpress instead of portal as a splashpage

### ISSUE THREAD

**Issue by eclcg** [mazi-project/portal#37]
În a situation where you are wanting users to log on the mazi-wifi, but they don't know what MAZI (or DIY/local networks) are, it would be helpful to come to the wordpress page as a splashpage, once you log on. This would allow you to explain the MAZI or the space where the MAZI is deployed, or give any other tipe of information.

**Comment by panosnethood** [comment]
Good point! We have already discussed this with Harris and we will check how easy to integrate the "MAZI" parts into a wordpress template that can then be adjusted based on the wordpress admin tools.

**Comment by haniavis** [comment]
The configuration of an application (Wordpress or Etherpad or other) as a splash page, instead of the default MAZI user interface, is integrated since version 1.8.6
