### ISSUE TITLE
connecting to a hidden WiFi network?

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#4]
Hi, I would like to connect my Raspberry Pi to a hidden local network for Internet access. Being "hidden" is not visible in the list of networks to connect at the "dual" mode. Would this be possible? In the worst case, could I do this through the terminal?

**Comment by andreasunteidig** [comment]
Where can I connect it to a WIFI generally? I can‘t see any list when switching to DUAL mode.

**Comment by haniavis** [comment]
You have to plug in a second USB WiFi dongle and you will see the corresponding section in the Networking tab.

From this section, you can choose the WiFi network to connect.

In dual mode, Internet is forwarded through the ethernet or through the second usb wifi dongle.

**Comment by haniavis** [comment]
The feature for connecting to hidden networks will be integrated in next versions.

**Comment by andreasunteidig** [comment]
Ah, that makes a lot of sense of course :)
Thanks!

**Comment by panosnethood** [comment]
I guess the simplest way to do this is to allow for an empty field for typing the WiFi network and not restricting it to a given list.

**Comment by andreasunteidig** [comment]
Now finally having a dongle, I can select a WIFI and tell it to connect. But nothing happens. I tried it both with a local WIFI as well as my phone-hotspot, which usually always works. What can I do wrong here?

**Comment by panosnethood** [comment]
Since Andreas brought it up, this is a very important feature for me. At work we have a hidden WiFi network and I cannot use at all the dual mode.

**Comment by andreasunteidig** [comment]
Which dongle model(s) are you guys using? I use an Edimax and it establishes connection both seldomly and random.

**Comment by panosnethood** [comment]
Check here for officially supported USB dongles: https://github.com/mazi-project/guides/wiki/Products

**Comment by andreasunteidig** [comment]
It's a EW-7811UN for Raspberry. I'll have to try the other one next week.

**Comment by panosnethood** [comment]
So, I have the same issue with version 1.6.5. I cannot connect to the Internet while in previous versions I could.

**Comment by haniavis** [comment]
could you be more specific?
do you see the available networks?
after writing the password of your desired network, what is happening?
do you see the message "Disconnected" inside the Connect to Wi-Fi Network box?

**Comment by andreasunteidig** [comment]
In my case, I can see the available networks, but nothing happens once I punch in the password and click on connect.
It just takes a while to process before going back to normal, showing „Active“ instead to „Connected to …“.

**Comment by panosnethood** [comment]
I had the same behaviour like Andreas but it was because of the antenna (I used a different one, TL-WN821N, that I thought it was working in the past, but it seems that it does not). So, this is the problem and we should stress in the guidelines that one should buy one of the suggested antennas.

**Comment by haniavis** [comment]
Since v1.6.7, you can connect to hidden WiFi networks + to passwordless WiFi networks.

There is also a text inside the "Connect to Wi-Fi Network" box with a link to the suggested antennas.
