### ISSUE TITLE
iOS: Captive Portal prevents use of MAZI recorder app

### ISSUE THREAD

**Issue by andreasunteidig** [mazi-project/portal#40]
With some MAZI zones (funnily not with any), iOS opens a captive portal. In order to use the browser or the recorder app, the user has to close it and to confirm that it is to be used without internet connection. This puts off a lot of user who don‘t know what to do. Can we somehow prevent the captive portal from opening?

**Comment by haniavis** [comment]
Thanks for reporting this, we will check it asap and come back with corrections.

**Comment by haniavis** [comment]
This is now solved since v2.5 with the integration of nodogsplash for the captive portal functionality
