### ISSUE TITLE
Creating instances in Guestbook

### ISSUE THREAD

**Issue by ingiH** [mazi-project/portal#42]
1. How do I create more than one instance of the Guestbook? I can easily create lots of instances that appear in the Administration Panel with different names, and the same URL, all pointing to the same guestbook. If I delete the Guestbook, and add it again, the same old one reappears. If I try to add something to the end of the URL to make a different instance, it is not recognised. It seems that the Zone only accepts one instance and the content cannot be changed or deleted, although the name and description can be changed. 

2. In the "Create new Application Instance" window it is not clear that the description section must be filled in in order to create an instance. There could be some text like "All fields must be completed", or the description section could be made optional.

3. I suggest that the dropdown menu in the "Create new Application Instance" window is at the top rather than the bottom as it is more conventional to select the "type" before entering details in an interface.

4. There is no indication of what the URL should be in the "Create new Application Instance" window.  I might guess that it should be - http://local.mazizone.eu:8081/ but I have to remember this before opening the window. Perhaps this should be filled in automatically by the Zone when the type of application is selected in the dropdown menu. However, see point 1 about only one instance allowed in the zone.

![new guestbook instance](https://user-images.githubusercontent.com/22938062/28469390-f400c886-6e2d-11e7-9e92-63e6e19ff731.png)

**Comment by panosnethood** [comment]
Thanks for the feedback! Until our developer team returns from vacation, I could quickly say that the Guestbook application cannot have multiple instances at this stage, but I agree that this would be a desirable feature.

As for moving the "type" option on top and automatically add some default content in the other two fields, I think that it is a very good idea and perhaps we could create a separate issue on it.

**Comment by haniavis** [comment]
Thanks for the detailed report!

For the moment you cannot create multiple instances of Guestbook.

We will take all your comments into account in the next release!

**Comment by haniavis** [comment]
This section of the admin portal is now fixed in v2.1.

You can create multiple instances only for some of the applications, Etherpad, Nextcloud, Framadate and the URL is automatically chosen.

We will add more in the future, in case we find specific deployments that need them.

**Comment by panosnethood** [comment]
only one point: if one cannot create additional instances for Guestbook and Interviews it shouldn't be possible to "delete" them from the list, but only disactivate them. Otherwise it wouldn't be obvious how to "bring them back" once deleted.

**Comment by haniavis** [comment]
In case you delete the one Guestbook or Interview instance you can then bring it back from the + button like the other applications.

Check the new version.
