### ISSUE TITLE
framework for translations/internationalization?

### ISSUE THREAD

**Issue by karless1** [mazi-project/portal#43]
ciao,

I'd like to translate the mazi interface, starting from the user's one, but also the admin interface should be translated. I'd like to propose mazi_zone it in different training situations, in France and Italy (digital self-defense and hacker pedagogy ateliers, in collaboration with alekos.net and ippolita.net), and a localized interface is important for the UX. I took a look at the code but I cannot understand how to do it, is there something like .po files?

thanks,

k.

**Comment by panosnethood** [comment]
Thanks for being interested in the MAZI toolkit! 

We have been discussing about the translation issue and your question is a good opportunity to develop an appropriate long-term framework for translating the admin interface.

**Comment by mgaved** [comment]
The MAZI toolkit is working with Translate Wiki to make the process easier, but  in the meanwhile the technical team have a list of all the core text here: https://github.com/mazi-project/portal/blob/master/locales/en.yml so you can take this list, translate to your preferred language, and send it back to the team (e.g. by attaching to a post on this list) so they can incoporate in the portal! thanks for your interest!

**Comment by karless1** [comment]
ciao

ok, I'll start the translation in Italian on that, and I'll send you the
results

thx

k.

Il 02/02/2018 18:22, mgaved ha scritto:
> The MAZI toolkit is working with Translate Wiki to make the process easier, but  in the meanwhile the technical team have a list of all the core text here: https://github.com/mazi-project/portal/blob/master/locales/en.yml so you can take this list, translate to your preferred language, and send it back to the team (e.g. by attaching to a post on this list) so they can incoporate in the portal! thanks for your interest!
> 
> 

-- 

"tecnologie appropriate"

GPG keys available via keyservers https://pgp.mit.edu/
Key fingerprint = BDFB 786F 6B35 7EB0 CE48 530C FCF9 E111 3537 3013

**Comment by haniavis** [comment]
The MAZI toolkit is now in the TranslateWiki Platform and you can log in there to translate the toolkit in different languages.
Check here for more info: https://translatewiki.net/wiki/Translating:MAZI_Toolkit
