### ISSUE TITLE
Restricted mode

### ISSUE THREAD

**Issue by gtcrea** [mazi-project/portal#44]
I can't enable restricted mode (the letter is grayed and the mouse pointer marks me forbidden). The documentation does not describe this mode well, can I have detailed instructions on how to activate it and if there are special accessories to enable it?

**Comment by panosnethood** [comment]
Hi! At this moment the "restricted" mode is not activated and you are right that it is not properly documented. The idea was to enable the administrator of a MAZI Zone to offer "restricted" access to the Internet if available (e.g., limit the total available bandwidth or enable a captive portal as in the offline case). And actually the name is not very good and when this mode will be finally implemented we will find a better name for it, perhaps "managed" or "controlled".

**Comment by haniavis** [comment]
Hi, as Panos said the "restricted or managed" mode is not yet implemented.

As soon as this feature is integrated in the MAZI toolkit, we will provide detailed instructions for its use.
