### ISSUE TITLE
Restricted or Managed mode

### ISSUE THREAD

**Issue by gtcrea** [mazi-project/portal#46]
In the "restricted" or "managed" or "ibrid" mode it would be nice to expect internet access to certain domains only.
Example : if I'm in offline mode and I have a local wordpress page with a link (remote) to a youtube video, have the ability to make the "youtube.com" domain as authorized, to play the video.
Sorry for my bad English, I hope to be clear.

**Comment by panosnethood** [comment]
Yes, ideally we should integrate an already existing open source "captive portal" software, because such functionality can become complicated. We are working on this ...
