### ISSUE TITLE
Networking mode (offline/dual) not indicated 

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#48]
After a clean installation of version 1.8.5, I changed the URL, connected the Raspberry Pi to the Internet through ethernet cable, changed to dual mode, updated to latest version, and then at the administrator panel the selected mode is not visible anymore but I can still choose one of them. Can you reproduce?

**Comment by haniavis** [comment]
This could happen after a false update and is now fixed in version 2 of the toolkit.

Thanks for reporting!
