### ISSUE TITLE
splash page option should be unique

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#49]
Nice feature allowing application to become the splash page! But it is confusing that I can add more than one because it can be only one actually. So, it would help when I choose one application as splash page all the other to get disactivated.

**Comment by haniavis** [comment]
Hi Panos

splash page is unique. You can not select more than one and if you select one, the previous one is automatically disactivated

**Comment by panosnethood** [comment]
I just tried it and I could activate more than one ...

**Comment by panosnethood** [comment]
this bug re-appeared in the latest versions ...

**Comment by ardadouk** [comment]
Hi Panos,
some more information is needed in order to debug this.
What browser are you using?
Is refreshing the page a 'solution' to this issue?

**Comment by panosnethood** [comment]
It happened with firefox on ubuntu and MAC (someone else told me about it). I don't remember refreshing the page (but in the past this was not needed). I can check again later tonight.

**Comment by ardadouk** [comment]
On version 2.5.3 this should be fixed.
