### ISSUE TITLE
info about memory available on filesystem

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#50]
It would be very useful for the MAZI Zone admin to be informed about the total memory available on the SDcard, somewhere in the dashboard perhaps (system info, or something like this). And add a small note that this can be expanded to more than 8GB with the raspi-config tool.

**Comment by haniavis** [comment]
This is reported in the User interface, check storage [here ](http://demo.mazizone.eu:4567/index_statistics)

There is also a recommendation in the Initial Configuration tab in the "[Admin Documentation](http://demo.mazizone.eu:4567/admin_documentation)" to expand the file system with the raspi-config tool.

Do you think we still need it in the dashboard?

**Comment by panosnethood** [comment]
Not necessarily but "Statistics" is not a good menu item for such information. I would call it "system" or something like this. And it would be nice to have it also somewhere in the admin panel. It would be nice also to show exactly how many GBs are available ...

**Comment by panosnethood** [comment]
Similar to this, it would be also nice to include in the documentation, what steps are required to add an external USB drive and use this space in different applications (e.g., nextCloud)
