### ISSUE TITLE
Multiple application instances

### ISSUE THREAD

**Issue by haniavis** [mazi-project/portal#56]
Looking at  #42 issue, we are wondering if and for which of our applications is meaningful to have multiple instances.

For example, it is meaningful for Wordpress in order to create multiple website.

What about Etherpad? I don't think so...

NextCloud? Yes because you could have multiple shared folders

Framadate? I don't think so...

Interview archive? I don't think so...

What about the Guestbook?

**Comment by panosnethood** [comment]
For NextCloud you don't need multiple instances to have multiple shared folders. I would say it is not needed.

For Guestbook, my opinion is that there are very few scenarios that I can imagine this making sense. I would leave it for later.

And for Wordpress, again, perhaps it is too much also in terms of load (?). Not sure for this, and I would wait for someone to ask as part of a concrete case study.

**Comment by haniavis** [comment]
With multiple instances, I meant different "boxes" in the user interface. 
So we need multiple instances for: 
- Nextcloud (which will be shared folders within the same Nextcloud installation)
- Etherpad (which will be different pads of the same etherpad installation)
- Framadate (which will be different polls in the same Framadate installation)

We will see in the future if there is the need to have another Guestbook instance or another Interview-archive instance or another WordPress instance.

In v2.1 the administrator will be able to check only the above 3 applications to add a new instance.
