### ISSUE TITLE
Password not working // Could be wrong password

### ISSUE THREAD

**Issue by zku-berlin** [mazi-project/portal#59]
Dear all,
I started working on the MAZI recently in order to create a local library for the artistic residency of the ZK/U based in Berlin. We have the Raspberry Pie in our possession since a wile now but lost the password to access the backend of the MAZI.

I am now trying to login on the raspberry pi as described on this document (http://nitlab.inf.uth.gr/mazi-guides/setup.html#change-the-password-of-the-pi-user). But when I put **pi** as a username and **raspberry** as a password it doesn't let me in. 

Could it be that I need the passwords and usernames that we lost to login?
If yes how can I create new ones?

Thank you very much in advance for your help that will be very needed.

Charles

**Comment by panosnethood** [comment]
Hi Charles,

The default ssh password for the user pi is "mazizone". See also here: http://demo.mazizone.eu:4567/admin_documentation

To reset the *mazi_admin* password you will need to ssh to the raspberry pi, and then run these commands: 
sudo su 
cd /root/back-end 
sh mazi-resetpswd.sh

See also: https://github.com/mazi-project/guides/wiki/Troubleshooting

**Comment by zku-berlin** [comment]
![24169541_10156018538794444_1104409780_o](https://user-images.githubusercontent.com/34035517/33281139-83f161ae-d3a4-11e7-808c-ef1fb5ab8180.jpg)
Thank you so much !
I logged in successfully and ssh the raspberry pi.
However the last command (sh mazi-resetpswd.sh) can't be opened. I attach a picture hoping it helps.

Thanks again

**Comment by haniavis** [comment]
Hi Charles,

Can you check if the mazi-resetpswd.sh file is in your mazizone?
Run the folllowing commands:
sudo su
cd /root/back-end
ls -l
Now you should see a list of files and one of them should be mazi-resetpswd.sh

If not,  you can update your mazizone backend with the following commands, after you successfully connect to the raspberry with the ssh command run the following:
sudo su
cd /root/back-end
git pull
sh mazi-resetpswd.sh

Harris

**Comment by zku-berlin** [comment]
![24169541_10156018538794444_1104409780_o](https://user-images.githubusercontent.com/34035517/33328032-34243dc6-d459-11e7-8384-3181f4b39688.jpg)

Hi both,
Fitst, thank you both so much for helping me out and I apologize to ask so much of your time.

The mazi-resetpswd.sh is not within the files of the mazizone and I can not run the following : 
sudo su
cd /root/back-end
git pull
sh mazi-resetpswd.sh
 
I think I'me unable to access the github. (see picture attached) Could it be that I have to connect the mazi to internet to do so? If yes can I do it without the admin password?

Thanks for your help,
Charles

**Comment by zku-berlin** [comment]
Hi both,
Fitst, thank you both so much for helping me out and I apologize to ask so much of your time.

The mazi-resetpswd.sh is not within the files of the mazizone and I can not run the following :
sudo su
cd /root/back-end
git pull
sh mazi-resetpswd.sh

I think I'me unable to access the github. (see picture attached) Could it be that I have to connect the mazi to internet to do so? If yes can I do it without the admin password?

Thanks for your help,
Charles
![24167571_10156020854119444_1981851733_o](https://user-images.githubusercontent.com/34035517/33328155-8781c092-d459-11e7-95ad-5176c2aecd69.jpg)

**Comment by panosnethood** [comment]
Yes, you need Internet access and you can do it without the admin password. The way is to connect the Raspberry Pi to your home Internet router or any router with Internet access with an ethernet cable (typically there are multiple yellow ports behind the router for connecting external devices to the Internet).

Otherwise, you will need to copy the file using a similar command to ssh, scp. The command would be:
scp mazi-resetpswd.sh pi@10.0.0.1:/home/pi/

to run this successfully you need to have copied the "mazi-resetpswd.sh" file to your computer. I could explain more if you cannot solve the problem with the ethernet cable ...

**Comment by panosnethood** [comment]
Btw, the reason (probably) this script is not in your MAZI Zone is that the version installed is an older one. The "git pull" command actually updates your installed version with the latest one including this script. If you cannot run this command then the alternative is to copy the file manually (with the scp command).

And also, your experience with the toolkit and problems that appear are extremely useful for us to make sure that they don't happen to other people, or if they do our guidelines are detailed enough to help those people solve the problem on their own.

So, we should thank you :-)

**Comment by zku-berlin** [comment]
Hi you both !
Finally I was able yesterday to update the Mazi, integrate the resetpswd file and reset the admin. password! 
The mission is a success and that's thanks to you two !

**Comment by panosnethood** [comment]
Great that you made it! Looking forward to listen to your stories using the MAZI toolkit :-)
