### ISSUE TITLE
import/export

### ISSUE THREAD

**Issue by deckspace** [mazi-project/portal#6]
When testing this new function, created two profiles. The first, held a set of four customised application views, one for the guestbook, two etherpads and one shared nextcloud directory. This profile was saved and exported to local PC. 

Next we made another profile, creating a custom set of application views with a different portal background image. This was saved and exported. 

When the first profile was reselected the toolkit rebooted ( I think) and the essid and most other settings, custom applications etc were restored. However the application title and subtitle welcome message and background image was not updated and continued to display info from the second profile.

As we had earlier saved the theme in the Appearance section was able to recover stored details ! otherwise I fear they would have been lost. So the Export/Import options don't handle all the settings. did I miss something?

The term Applications is confusingly used in two contexts in the admin interface. Perhaps the applications [etherpad, nextcloud etc] should be referred to as 'tools' in the toolkit and portal 'application title' should instead be Mazizone title and subtitle. eg. give your Mazizone a title..

**Comment by haniavis** [comment]
The import/export functionality is saving everything (network configurations, applications, application instances, notifications, etc) except the visual configurations (background image, title, subtitle etc.)

All the visual configurations should be saved as a "Theme" from the Appearance tab.

The above are explained on the top of the Import/Export tab.

If we think it is worthy, we could integrate these two (snapshot and appearance) in a single import/export functionality, in the future.

**Comment by deckspace** [comment]
thanks for the clarification.. I guess my point was more that we can't export/import appearance settings as we can the general portal config.

**Comment by panosnethood** [comment]
Hi James, you can export/import appearance settings but with a different interface: By "Save/Load" buttons in appearance page: http://demo.mazizone.eu:4567/admin_configuration

But I think that this is confusing (having two different places to save the current configuration divided in two "parts") and I propose to indeed merge them at some point.

**Comment by haniavis** [comment]
James here says that he can save the appearance settings from the corresponding tab, but he can not export them into a file, which is true.

We will integrate the two different export/import parts (conf and appearance) in the next version and you will be able to export all of them into a single file.

**Comment by haniavis** [comment]
This feature is now integrated in v1.6.1
