### ISSUE TITLE
Create two different boxes for USB WiFi dongle and OpenWRT router in the dashboard

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#61]
This is mentioned in #54 and https://github.com/mazi-project/guides/issues/4 but I create a separate issue since this is more urgent than the other two because it can create confusion.

Find below the "single" box that should be divided in two:

![screenshot from 2017-11-30 17-05-22](https://user-images.githubusercontent.com/17811877/33440605-b7278816-d5f0-11e7-8faa-77d289ef6617.png)

**Comment by panosnethood** [comment]
Actually there is not need for a second box since the "Connect to WiFi" already covers the case of the USB dongle. What should be done as a first step would be to rename the box above to "Add router as access point" or something like this and rename the button to "Add router"

**Comment by haniavis** [comment]
This is now solved in v2.2
