### ISSUE TITLE
change the disactivated mode "restricted" to "managed", or?

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#62]
This is still not activated but there have been many complains about this, so perhaps we could change it already.

**Comment by panosnethood** [comment]
And while the change takes place, feel free to brainstorm here about other possible names for this mode, which is meant to offer Internet access but not "unconditional". It could be subject to the acceptance of the "terms of use", it could include a "cap" set by the admin, it could limit the web sites accessible, etc.

**Comment by mgaved** [comment]
I like the term "Managed" - but there needs to be text in an information window explaining what the term means. This could be a short description which links to the Documentation section which explains in more detail what it means, and how to set up and configure it.

**Comment by deckspace** [comment]
this is a comments not complaints forum! What conditions for connection need to be managed? Anything that isn't listed in Offline or Internet (dual?) mode.. it's still not at all clear..

**Comment by panosnethood** [comment]
These are two related suggestions #46 (white list), #34 (shaping). In my mind this is a complex "mode" that we might even avoid implement if we don't find a good open-source "captive portal" solution that can be supported on a Raspberry Pi.

**Comment by deckspace** [comment]
A review of the captive portal options seems to be required. Other 
options are available.
Mac address whitelisting and the shaping of the available bandwidth are 
best done on the upstream router
