### ISSUE TITLE
Php 7 in wordpress

### ISSUE THREAD

**Issue by gtcrea** [mazi-project/portal#64]
It would be nice to have the latest version 7 of php (faster and less memory consumption) on local  wordpress, now compatible with most of plugins.

**Comment by deckspace** [comment]
a year on from the early versions of the toolkit several applications and services have major updates.. php, nextcloud, wordpress, etherpad also I expect. The raspberry Pi firmware also had updates, does this get done during mazi upgrade?

**Comment by haniavis** [comment]
The update of applications (nextcloud, php etc.) is going to be added in one of the next releases

**Comment by gtcrea** [comment]
8 months have passed but still no php update ...

**Comment by haniavis** [comment]
Hi, we are working on a major update to raspbian stretch, so stay tuned for v2.6 which will include php 7.

**Comment by gtcrea** [comment]
Ok thanks, will be compatible with Raspberry Pi 3 Model B+ ???

**Comment by haniavis** [comment]
Yes, that's the point, to support rpiB+. We are fine-tuning the update and will be released hopefully in about a month.

**Comment by haniavis** [comment]
The toolkit v3 has php 7, so this can be closed now.
