### ISSUE TITLE
Nextcloud update?

### ISSUE THREAD

**Issue by deckspace** [mazi-project/portal#68]
the preloaded Nextcloud is V11 rather than V12 current. It is possible to login and update to the current version but we found that it is then no longer possible create fresh group and user accounts as the default - 'mazizone' password for admin is no longer accepted.

**Comment by deckspace** [comment]
further attempts proved successful. perhaps a system reboot helped.. ?

**Comment by haniavis** [comment]
I guess this can be closed now
