### ISSUE TITLE
first contact and important admin tasks

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#7]
I think it would be useful to make "obligatory" the most important admin tasks on "first contact", and especially the change of password.

For this, it would be great if we could detect the "first usage" of a MAZI Zone and especially then prompt also for a new SSID, draw attention to the date/time, etc.

**Comment by deckspace** [comment]
If the default password hasn't been changed then the prompt should continue to be presented

**Comment by haniavis** [comment]
This feature is integrated in v1.6.1
