### ISSUE TITLE
Wordpress file upload

### ISSUE THREAD

**Issue by deckspace** [mazi-project/portal#70]
The default media file upload in the apache2/php.ini file is set as 2mb when it should be at least 20mb or more, can this please be adjusted in the template file or can a configuration option be added somewhere accessible for non shell users.. ? I tried adding a plug in to set in the interface but it didn't work for us.

**Comment by haniavis** [comment]
We can give the option to the admin to change it through the administration panel since it is related to other applications also, not just Wordpress.

Will be included in the next versions.

**Comment by deckspace** [comment]
thanks, how can I fix it now?

**Comment by haniavis** [comment]
Edit in file /etc/php5/apache2/php.ini the variables:
post_max_size
upload_max_filesize

**Comment by haniavis** [comment]
This can now be edited through the admin interface, in the settings page, since v2.4.1.
