### ISSUE TITLE
small text typos to be corrected in v2.2 release

### ISSUE THREAD

**Issue by mgaved** [mazi-project/portal#75]
Hi folks: some small typos  (spelling errors) to be corrected in v2.2 release, thanks!

Admin Password set up screen

Change: “bellow” to “below” . 
Change: “adminstration” to “administration”.

Date/Time setup screen:
Spelling mistake
Change: “bellow” to “below” . 

Wireless Interface setup screen:
Spelling mistake
Change: “bellow” to “below” . 

MAZIzone Applications (main screen)
Spelling mistake
Change: “bellow” to “below” .

MAZI zone Monitoring (http://portal.mazizone.eu/admin_monitor)
Change: “bellow” to “below” . 

MAZI zone Devices (http://portal.mazizone.eu/admin_devices)
Change: “bellow” to “below” . 

Sensor measurements:
Change: “bellow” to “below” . 

MAZi zone network settings
Change: “rasberry” to “Raspberry”

Reboot pop up window:
Change: "Procced" to "Proceed".

thanks!

**Comment by haniavis** [comment]
Thanks for this!

will be integrated in v2.3
