### ISSUE TITLE
menu bar too big at the top on a mobile phone

### ISSUE THREAD

**Issue by raot** [mazi-project/portal#77]
When you use mazizone to provide mobile phone users with some services, the menu bar on top is quite large (in height) and uses up too much screen estate imho.

suggestion: line 1 ith Title ("MAZI Zone Portal" by default) and the three bars for the menu is okay on top, even the bell with the indication for incoming messages could be moved to that first line. then, the links and date/time display could be moved to the bottom of the page, along with other infos even maybe.

**Comment by haniavis** [comment]
Hi,

you can update to v2.3.1 which fixes the menu bar in the smartphone view.

Thanks for your feedback and your valuable suggestions!
