### ISSUE TITLE
camera view

### ISSUE THREAD

**Issue by deckspace** [mazi-project/portal#78]
I was sent a screen shot by a local mazi user showing the portal view of the camera which once showed the live video feed to the left of the window but now shows a refreshing broken link gif instead. In the admin view (once logged in) the camera configuration, the live feed is showing fine. 
his reminded me I had also seen this on a mazi toolkit running in our lab so I checked and that's the same for us here as well..

**Comment by haniavis** [comment]
Hi,

could you tell us your version and if you experienced this after an update?

A screenshot also would be good to identify the issue.

**Comment by deckspace** [comment]
Hi H
I sent you a similar screenshot in the bundle the other day.. did you not see that?

**Comment by mgaved** [comment]
I'm running v2.3.1 and I don't find this error, it works ok on mine.  For information though, I formatted an SD card, loaded v2.3 from fresh, then upgraded to v2.3.1. So I can't tell you if it's an issue if you upgrade to v2.3 from an earlier version. James: do you know which version the user is running and if they've gone through the upgrade path to v2.3? (wondering if its a particular version issue, or upgrade path?)
