### ISSUE TITLE
small text typos in v2.3.1

### ISSUE THREAD

**Issue by mgaved** [mazi-project/portal#81]
Hi developer team - some small typos I've come across in v2.3.1

- is it ok to put these here, or do you have an alternative way for me to report, e.g. should I download the text file and send over an edited version where I've found spelling mistakes?
(https://github.com/mazi-project/portal/blob/master/locales/en.yml)

Default text on intro
"Welcome to the MAZI Zone Applications Portal, please use the links bellow to navigate to the applications offered by this MAZI Zone."

Spelling mistake: please change "bellow" to "below"

Admin: Check for Updates
Pop up window spelling mistake when “Check for Updates”

“Update proccess” – spelling mistake – change to “process”.

MAZIzone GuestBook Admin (http://portal.mazizone.eu/admin_guestbook)  
Moderate Posted Content
"Use the button bellow" change "bellow" to "below"

Background Image:
"You can use the form bellow"  – spelling mistake –  change "bellow" to "below"

Welcome Message
"You can use the form bellow" – spelling mistake –  change "bellow" to "below"

Maximum File Size for uploads
"You can use the form bellow" – spelling mistake –  change "bellow" to "below"

Tags:
"You can use the input field bellow" – spelling mistake –  change "bellow" to "below"

Auto Expand Comment
"You can use the button bellow" – spelling mistake –  change "bellow" to "below"

Submision Name Requirement
"Submision" – spelling mistake –  change to "Submission"
"You can use the button bellow" – spelling mistake –  change "bellow" to "below"

thanks!

**Comment by panosnethood** [comment]
Hi, I tried to correct the above typos doing a fork in my own github repository, https://github.com/panosnethood/portal/commit/4331dc53bab9ddbc60ecb432232b8e3824d87712, but not sure how to do a pull request out of it. Any hints? :-)

**Comment by haniavis** [comment]
This can be closed.

Thanks both for your feedback!
