### ISSUE TITLE
External Dependency Requires Internet Access

### ISSUE THREAD

**Issue by hellekin** [mazi-project/portal#82]
## Problem
Some application(s) depend(s) on Google's AJAX API that requires Internet access to load. In the case the Mazizone is not connected, e.g., the admin login may not work. 

## Solution
Include the necessary scripts and assets directly into the repository to avoid external dependencies on Internet connection.

**Comment by panosnethood** [comment]
Thanks! I personally never had problems with offline installations of the MAZI toolkit. Could you give an example of an application that uses these dependencies, just to be more precise?

**Comment by haniavis** [comment]
We can consider this closed, since no one else reported something like this before.

The toolkit integrates all the necessary scripts and code to work offline.
