### ISSUE TITLE
Remove the flags from the language menu

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#84]
Hi, I received twice the comment regarding the American flag for english and in general I personally don't like the use of flags for languages. And I don't see them used often anyway. So, I would just remove them and leave the language name in short (EN, EL, etc) or in full.

**Comment by haniavis** [comment]
The English flag is now fixed in v2.4.1

**Comment by mgaved** [comment]
MAZIzones now being used in Guyana, South America. We have had a new request for the flags to be removed as this is a sensitive issue: Guyana is an ex British colony so claiming the English language belongs to the UK is not received well. How can we remove the flags? I agree with Panos that it should just have a language name abbreviation.
