### ISSUE TITLE
Customising arrangement of app icons on Applications Portal page

### ISSUE THREAD

**Issue by mgaved** [mazi-project/portal#91]
In the Administrator interface I can turn on and off the applications I wish to have shown in the users' interface (http://[mazizone]/admin_application )

How can I customise the sequence so they appear in the order I want them to appear (left to right) in the users' interface. Currently with some applications switched on and others switched off, they don't appear in the order I would like (I would like the most important to me in the top left, and least important at the bottom of the list). 

Also there are some gaps in the layout when I don't have all the applications turned on. Can I re-arrange how the icons appear so there are no gaps?

thanks!

**Comment by haniavis** [comment]
There is a new sorting functionality in v2.5.5 which helps you re-order the application instances.
