### ISSUE TITLE
Explicit information/ user interaction needed on Updates window

### ISSUE THREAD

**Issue by mgaved** [mazi-project/portal#93]
(discussed in email but moved to here so it is generally known)

When you upgrade from v2.4 to v2.4.1 a support window appears ("Check for Updates") asking the administrator-user "please wait several minutes and then refresh this page".

This is not clearly defined, and there is a risk that an administrator refreshes the page before the upgrade has fully completed and causes an error, or at least administrator confusion.

A clearly defined interaction is needed to help administrators know when it is right to refresh the page.

![mazizonev2_4-updating](https://user-images.githubusercontent.com/18211485/37464664-f23bbec4-2850-11e8-917b-3c9bae75f988.png)

NOTE: MAZI-technical developers have noted (12/03): "We are in the process of redesigning the update procedure. The most probable solution is to force the reboot and start the wifi AP only as soon as the update is complete. "

I think this would be a good solution, with a change of text on the "Check for Updates" pop-up window, For example: "This MAZIzone is now being updated, Please do not refresh the screen or attempt to connect to the MAZIzone: it will automatically reboot once the update has completed, then you can continue,."

**Comment by haniavis** [comment]
Thanks Mark for the text, it will be used for the update box.

**Comment by haniavis** [comment]
This is now solved with the new Update process integrated in v2.4.6. 

As soon as the user clicks Update, the raspberry is automatically rebooted and it turns on the WiFi network as soon as the Update process is fully completed.
