### ISSUE TITLE
not possible to add custom applications at the MAZI portal

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#98]
Hi! I created on the terminal a new simple folder with an index.html. I added a new application pointing to it but it does not work. 

Perhaps we need to add "Other" in the list of applications? 

Or how can someone add manually a new application in the portal?

**Comment by haniavis** [comment]
Hi, for the moment you can't add a new application in the portal., even if you are experienced enough to add it manually in the system.

I agree that it would be a nice addition to add a button "other" in the applications tab.

**Comment by haniavis** [comment]
You can now add custom applications at the MAZI Portal through a button in the Applications tab.
