### ISSUE TITLE
mazi toolkit image not compatible with Rpi 3 B+

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#99]
This is already discussed in the e-mail list, but I place it also here for those that do not follow the list .,.

**Comment by mgaved** [comment]
The two radios on the Rpi 3B+ make networks of MAZIzones (including meshing) a real possibility so I am in favour of this model being supported.

**Comment by haniavis** [comment]
Since v3.0.1 of the toolkit, the rpi3B+ is supported.
